export default {
  LOAD_ITEMS_LOADING: 'FETCH_ITEMS_REQUEST',
  LOAD_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  LOAD_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',

  LOAD_ITEM_LOADING: 'FETCH_ITEMS_REQUEST',
  LOAD_ITEM_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  LOAD_ITEM_FAILURE: 'FETCH_ITEMS_FAILURE',
};
